version: '3'

services:
  neo4j_ker_ko:
    image: neo4j:4.1.1
    hostname: neo4j_ker_ko
    container_name: neo4j_ker_ko
    restart: always
    ports:
      - "8043:7474"
      - "7683:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/logs:/logs
      - .:/knowledge-management-system/
      - log:/knowledge-management-system/log

    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
      NEO4J_dbms_directories_import: /
      NEO4J_dbms_tx__log_preallocate: "false"
      NEO4J_dbms_tx__log_rotation_retention__policy: "false"
      NEO4J_dbms_security_procedures_whitelist: "gds.*, apoc.*"
      NEO4J_dbms_security_procedures_unrestricted: "gds.*, apoc.*"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS: "graph-data-science, apoc"
    extra_hosts:
      host.docker.internal: 172.17.0.1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  docsearch:
    build: ./apps/ker_ko/document_based
    image: docsearchimg
    container_name: docsearch
    ports:
        - "8993:8007"
    volumes:
        - .:/docbased
    extra_hosts:
       host.docker.internal: 172.17.0.1
    command: python -m apps.ker_ko.document_based.main

  classifier:
    image: adoptopenjdk/openjdk8
    container_name: koclassifier
    volumes:
      - ./apps/ker_ko/dataset/models/classifier/korean_bert/:/ker_ko
    command: java -jar ./ker_ko/lgai-mecab-1.0.0.jar

  htmltransformer1:
    build:
        context: ./apps/ker_ko/xslttransformer
    container_name: htmltransformer
    ports:
        - "8096:8081"
    volumes:
        - ./apps/ker_ko/xslttransformer:/xslttransformer
    command: java -jar ./com.lge.xslttranformer-0.0.1-SNAPSHOT.jar

  kms_ker_ko:
    image: kms_ker_ko
    hostname: kms_ker_ko
    container_name: kms_ker_ko
    ports:
      - "8083:8083"
      - "8008:8007"
    build:
      context: .
      dockerfile: Dockerfile_ker_ko
    volumes:
      - .:/knowledge-management-system
    extra_hosts:
      host.docker.internal: 172.17.0.1
    depends_on:
      - neo4j_ker_ko
      - classifier
    links:
      - neo4j_ker_ko
      - classifier

volumes:
  log: {}


